export type NodeCategory =
  | 'project'
  | 'structure'
  | 'design-phase'
  | 'member'
  | 'load'
  | 'ai'
  | 'standard'
  | 'tool'
  | 'document'
  | 'special';

export interface GraphNode {
  id: string;
  label: string;
  labelEn?: string;
  category: NodeCategory;
  size: number; // 1~5
  description: string;
  details?: Record<string, string>;
  aiOpportunity?: string;
  phase?: number;
}

export interface GraphLink {
  source: string;
  target: string;
  label?: string;
  strength?: number;
}

export const NODE_COLORS: Record<NodeCategory, string> = {
  project:        '#00d4ff',
  structure:      '#ff6b35',
  'design-phase': '#10b981',
  member:         '#f59e0b',
  load:           '#ef4444',
  ai:             '#7c3aed',
  standard:       '#64748b',
  tool:           '#0ea5e9',
  document:       '#ec4899',
  special:        '#14b8a6',
};

export const NODE_LABELS: Record<NodeCategory, string> = {
  project:        '프로젝트',
  structure:      '구조 시스템',
  'design-phase': '설계 단계',
  member:         '구조 부재',
  load:           '설계 하중',
  ai:             'AI 적용',
  standard:       '설계 기준',
  tool:           '소프트웨어',
  document:       '설계 문서',
  special:        '특수 검토',
};

export const GRAPH_NODES: GraphNode[] = [

  // ══════════════════════════════════════════════════════
  // AI 핵심 허브
  // ══════════════════════════════════════════════════════
  {
    id: 'ai-core',
    label: 'AI 구조설계',
    labelEn: 'AI Structural Design',
    category: 'ai',
    size: 5,
    description: '구조설계 전 과정에 AI를 통합하여 설계 자동화, 최적화, 지식 관리를 실현하는 핵심 전략. 4대 구조설계 영역(데이터센터·아파트·초고층·대공간)에 단계적으로 적용.',
    aiOpportunity: '설계 기간 30~50% 단축, 오류 70% 감소 목표. Phase 1~3 단계적 실행.',
    phase: 1,
  },

  // ══════════════════════════════════════════════════════
  // AI 로드맵 단계
  // ══════════════════════════════════════════════════════
  {
    id: 'ai-phase1',
    label: 'Phase 1: DB화·표준화',
    labelEn: 'Phase 1: Data & Standardization',
    category: 'ai',
    size: 4,
    description: '0~12개월. 설계자료 DB화, 업무 표준화, 암묵지 형식화(스킬화), AI 구조설계 TF 조직 구성.',
    details: {
      '기간': '0~12개월',
      '과제1': '설계자료 DB화 (구조설계·현장지원·안전진단)',
      '과제2': '용도별 구조설계도서 데이터 구축 (초고층·DC·대공간·아파트)',
      '과제3': '업무 표준화 및 스킬화 (암묵지 형식화)',
      '과제4': 'AI 구조설계 TF 조직 구성',
      '기대효과': 'AI 자동화를 위한 데이터·조직 기반 완성',
    },
    phase: 1,
  },
  {
    id: 'ai-phase2',
    label: 'Phase 2: 자동화 기반 구축',
    labelEn: 'Phase 2: Automation Foundation',
    category: 'ai',
    size: 4,
    description: '12~24개월. 구조시스템 대안 AI 검토, DB 기반 가정단면 자동화, 구조설계·안전진단 세분화 업무 자동화.',
    details: {
      '기간': '12~24개월',
      '과제1': '구조시스템 대안 AI 검토',
      '과제2': '기존 DB 기반 가정단면 추출 자동화',
      '과제3': '세분화된 구조설계 업무 자동화 (설계하중·모델링)',
      '과제4': '세분화된 안전진단 업무 자동화 (철근탐사·보고서)',
      '기대효과': '반복 업무 80% 자동화, 설계 기간 30% 단축',
    },
    phase: 2,
  },
  {
    id: 'ai-phase3',
    label: 'Phase 3: 지능형 설계 보조',
    labelEn: 'Phase 3: Intelligent Design Assistant',
    category: 'ai',
    size: 4,
    description: '24~36개월. 부재 단면 최적화 AI, 설계 변경 AI 검토, 구조설계 기준 적합여부 AI 검토, 구조도면-설계 일치여부 AI 검토.',
    details: {
      '기간': '24~36개월',
      '과제1': '부재 단면 최적화 AI 검토',
      '과제2': '설계 변경 내용 AI 검토',
      '과제3': '구조설계 기준 적합여부 AI 검토',
      '과제4': '구조도면-구조설계 일치여부 AI 검토',
      '기대효과': '설계 기간 50% 단축, 오류 90% 감소',
    },
    phase: 3,
  },

  // ── AI 세부 과제 ──────────────────────────────────────
  {
    id: 'ai-db-build',
    label: '설계자료 DB 구축',
    labelEn: 'Design Data DB',
    category: 'ai',
    size: 3,
    description: '구조설계·현장지원·안전진단 업무의 과거 설계자료를 체계적으로 DB화. 용도별(초고층·DC·대공간·아파트) 우선순위 결정 및 데이터 선별.',
    aiOpportunity: 'RAG(검색증강생성) 기반 AI의 학습 데이터 기반. 품질 높은 DB가 AI 성능을 결정.',
    phase: 1,
  },
  {
    id: 'ai-standardize',
    label: '업무 표준화·스킬화',
    labelEn: 'Work Standardization',
    category: 'ai',
    size: 3,
    description: '업무 전 과정을 세분화하고 표준화하여 정의. 숙련 엔지니어의 암묵지를 형식지로 변환(스킬화). AI 자동화의 전제 조건.',
    aiOpportunity: '표준화된 업무 단위가 AI 자동화의 입력 단위가 됨. 암묵지 형식화 → AI 학습 데이터화.',
    phase: 1,
  },
  {
    id: 'ai-prelim-section',
    label: '가정단면 자동화',
    labelEn: 'Preliminary Section Automation',
    category: 'ai',
    size: 3,
    description: '기존 DB 기반으로 유사 프로젝트의 가정단면을 자동 추출. 설계 초기 단계 시간 단축.',
    aiOpportunity: '기존 구로DC·ICN062·부평DC 데이터를 학습하여 신규 DC 프로젝트 가정단면 즉시 제안.',
    phase: 2,
  },
  {
    id: 'ai-load-calc',
    label: '설계하중 자동 산정',
    labelEn: 'Auto Load Calculation',
    category: 'ai',
    size: 3,
    description: '건물 용도·규모 입력 시 KBC 2019 기준에 따라 설계하중을 자동 산정. 설계하중표(엑셀) 자동 생성.',
    aiOpportunity: '설계하중표 작성 시간 90% 절감. midas Gen 자동 입력 파이프라인 연계.',
    phase: 2,
  },
  {
    id: 'ai-modeling',
    label: '구조해석 모델링 자동화',
    labelEn: 'Auto Structural Modeling',
    category: 'ai',
    size: 3,
    description: '구조 평면도 및 설계하중 데이터를 기반으로 midas Gen 해석 모델 자동 생성.',
    aiOpportunity: '모델링 시간 70% 절감. 설계 변경 시 모델 자동 업데이트.',
    phase: 2,
  },
  {
    id: 'ai-rebar-auto',
    label: '슬래브 배근도 자동화',
    labelEn: 'Slab Rebar Automation',
    category: 'ai',
    size: 3,
    description: 'CNP 슬래브 배근도 자동화 AI 프로젝트. 구조계산 결과를 기반으로 슬래브 배근도를 자동 생성.',
    aiOpportunity: '배근도 작성 시간 80% 절감. AutoCAD DXF 자동 출력 파이프라인.',
    phase: 2,
  },
  {
    id: 'ai-safety-diag',
    label: '안전진단 자동화',
    labelEn: 'Safety Diagnosis Automation',
    category: 'ai',
    size: 3,
    description: '철근배근탐사 판독 및 보고서 AI 자동화. 현장 탐사 데이터를 AI가 자동 분석하여 보고서 자동 생성.',
    aiOpportunity: '안전진단 보고서 작성 시간 70% 절감. 판독 오류 감소 및 일관성 향상.',
    phase: 2,
  },
  {
    id: 'ai-section-opt',
    label: '부재 단면 최적화 AI',
    labelEn: 'Section Optimization AI',
    category: 'ai',
    size: 3,
    description: '구조해석 결과를 기반으로 부재 단면을 자동 최적화. 경제성과 안전성을 동시에 만족하는 최적해 도출.',
    aiOpportunity: '재료비 10~20% 절감 목표. 설계 반복 횟수 대폭 감소.',
    phase: 3,
  },
  {
    id: 'ai-change-review',
    label: '설계 변경 AI 검토',
    labelEn: 'Design Change Review AI',
    category: 'ai',
    size: 3,
    description: '설계 변경 사항을 AI가 자동 검토하여 구조 안전성 영향 분석 및 수정 범위 자동 산정.',
    aiOpportunity: '설계 변경 검토 시간 80% 절감. 누락 검토 항목 방지.',
    phase: 3,
  },
  {
    id: 'ai-code-check',
    label: '기준 적합여부 AI 검토',
    labelEn: 'Code Compliance AI',
    category: 'ai',
    size: 3,
    description: 'KBC 2019, KDS 41 등 구조설계 기준에 대한 적합여부를 AI가 자동 검토.',
    aiOpportunity: '기준 검토 누락 방지. 검토 시간 90% 절감.',
    phase: 3,
  },
  {
    id: 'ai-drawing-check',
    label: '도면-설계 일치 AI 검토',
    labelEn: 'Drawing Consistency AI',
    category: 'ai',
    size: 3,
    description: '구조도면과 구조계산서의 일치여부를 AI가 자동 비교 검토. 오류 자동 감지.',
    aiOpportunity: '도면-계산서 불일치 오류 95% 자동 감지. 검토 시간 대폭 절감.',
    phase: 3,
  },

  // ══════════════════════════════════════════════════════
  // 4대 구조설계 영역
  // ══════════════════════════════════════════════════════
  {
    id: 'domain-dc',
    label: '데이터센터',
    labelEn: 'Data Center',
    category: 'project',
    size: 5,
    description: '장스팬 구조, 고중량 장비하중(10~21 kN/m²), 복합구조 시스템(RC+철골+SRC+PT). AI 파일럿 1순위 영역.',
    aiOpportunity: '서버랙 하중 변동 대응 자동화, 복합구조 접합부 자동 설계.',
  },
  {
    id: 'domain-apt',
    label: '아파트',
    labelEn: 'Apartment',
    category: 'project',
    size: 3,
    description: '표준화된 평면, 반복 구조. AI 학습 데이터 풍부. 배근도 자동화 최적 영역.',
    aiOpportunity: '표준 평면 기반 구조 자동 설계 및 배근도 자동 생성.',
  },
  {
    id: 'domain-highrise',
    label: '초고층',
    labelEn: 'High-Rise',
    category: 'project',
    size: 3,
    description: '복잡한 구조 시스템, 풍하중·지진하중 지배 설계. 고급 AI 해석 필요.',
    aiOpportunity: '풍동실험 데이터 연동 AI 해석, 아웃리거 시스템 자동 최적화.',
  },
  {
    id: 'domain-longspan',
    label: '대공간',
    labelEn: 'Long-Span',
    category: 'project',
    size: 3,
    description: '트러스, 스페이스프레임, 케이블 구조. 형태 최적화 AI 적용 가능.',
    aiOpportunity: '생성형 AI를 활용한 구조 형태 최적화 및 위상 최적화.',
  },

  // ══════════════════════════════════════════════════════
  // 데이터센터 프로젝트
  // ══════════════════════════════════════════════════════
  {
    id: 'dc-guro',
    label: '구로 데이터센터',
    labelEn: 'Guro DC (22-GM-139)',
    category: 'project',
    size: 4,
    description: '서울시 구로구 개봉동 166-2번지. 지하5층/지상8층, 방송통신시설 중 데이터센터. 2023년 착공용 실시설계 완료. 724페이지 구조계산서.',
    details: {
      '프로젝트번호': '22-GM-139',
      '규모': '지하 5층 / 지상 8층',
      '구조방식': 'RC + 철골 + SRC 복합',
      '기초형식': '지내력기초 (연암·경암)',
      '설계지지력': 'Fe ≥ 1,200 kN/m²',
      '지하수위': 'EL+5.68m (GL-6.42m)',
      '부상방지': '영구배수공법',
      '내진등급': '내진등급 1 (IE=1.2)',
      '지진해석': '응답스펙트럼해석법',
      '계산서': '724페이지 실시설계 구조계산서',
    },
    aiOpportunity: '724페이지 구조계산서 자동 생성·검토 AI 적용 가능. 층별 콘크리트 강도(fck 30~49MPa) 자동 산정, PT 텐던 배치 자동 최적화.',
    phase: 2,
  },
  {
    id: 'dc-icn062',
    label: '인천 가좌 테크센터',
    labelEn: 'ICN062 (AWS DC)',
    category: 'project',
    size: 4,
    description: '인천광역시 서구 가좌동 585-1. 데이터센터(지하1/지상8층) + 주차동(3층) + 방문자센터(3층) + 수소저장소(1층) 복합 개발. AWS 발주.',
    details: {
      '프로젝트번호': '2023-050',
      '규모': '데이터센터 지하1/지상8층 + 부속동',
      '콘크리트(DC)': 'fck=24MPa(슬래브/보), 30MPa(기둥/벽체)',
      '콘크리트(기초)': 'fck=30MPa',
      '철근': 'SD500(D10~13), SD600(D16~35)',
      '특이사항': '수소저장소 특수하중 별도 적용',
      '증축고려': '주차동 1개층 증축 계획 반영',
      'DATA HALL 활하중': '21.0 kN/m² (2F)',
      'GENERATOR ROOM 활하중': '20.0 kN/m² (3~7F)',
      'MECHANICAL DECK 활하중': '10.0 kN/m² (2F)',
    },
    aiOpportunity: '다동 복합 개발 시 용도별 하중 조합 자동화 AI 적용 가능. 설계하중표(엑셀) → 구조해석 모델 자동 입력 파이프라인.',
    phase: 2,
  },
  {
    id: 'dc-bupyeong1',
    label: '부평 데이터센터 1단계',
    labelEn: 'Bupyeong DC Phase1 (22-GM-096)',
    category: 'project',
    size: 3,
    description: '부평 데이터센터 1단계. 실시설계(CD100% REV.01) 완료. 지하구조물 내진설계, 유류탱크 구조 포함.',
    details: {
      '프로젝트번호': '22-GM-096',
      '설계단계': '실시설계 CD100% REV.01',
      '특수구조': '유류탱크 적재받침대',
      '지하내진': '지하구조물 내진설계 포함',
      '타워크레인': '타워크레인 좌대 검토 포함',
    },
    aiOpportunity: '1단계 설계 데이터를 학습하여 2단계 설계 자동화 적용 가능한 최적 파일럿 케이스.',
    phase: 2,
  },
  {
    id: 'dc-bupyeong2',
    label: '부평 데이터센터 2단계',
    labelEn: 'Bupyeong DC Phase2 (2023-205)',
    category: 'project',
    size: 3,
    description: '부평 데이터센터 2단계 신축설계. 철골보 접합상세(전단·모멘트접합), 지상층 풍도 구조 검토 포함.',
    details: {
      '프로젝트번호': '2023-205',
      '설계단계': '중간설계 → 실시설계',
      '접합상세': '철골보 전단접합·모멘트접합',
      '풍도검토': '지상층 풍도 구조 검토',
      '유류탱크': '유류탱크 적재받침대 SHOP 도면',
    },
    aiOpportunity: '철골보 접합부 자동 설계 AI 적용 대상. 1단계 데이터 연계 학습.',
    phase: 2,
  },
  {
    id: 'dc-gimpo',
    label: '김포 데이터센터',
    labelEn: 'Gimpo DC (2024-177 ICN11)',
    category: 'project',
    size: 3,
    description: '2024년 착공도서 CD100% REV.3 완료. midas Gen 모델(거더·기둥·코어벽체 분리 모델) 및 설계하중표 완비.',
    details: {
      '프로젝트번호': '2024-177 (ICN11)',
      '설계단계': 'CD100% REV.3',
      '해석모델': '거더·기둥·코어벽체 분리 모델',
      '설계하중': '250207-RPT-ICN11R-설계하중-0014.xls',
      '특이사항': '수평 분리타설 검토 포함',
    },
    aiOpportunity: '최신 프로젝트로 AI 설계 검토 도구 파일럿 적용 대상. 분리 모델 자동 통합 AI.',
    phase: 2,
  },
  {
    id: 'dc-incheon',
    label: '인천 데이터센터',
    labelEn: 'Incheon DC (22-GM-192 ICN01)',
    category: 'project',
    size: 3,
    description: '인천 데이터센터(ICN01). 착공도서 완료. BOD(Basis of Design) 문서 및 DD100% 도서 완비.',
    details: {
      '프로젝트번호': '22-GM-192',
      '설계단계': '착공도서 완료',
      'BOD문서': 'BASIS OF DESIGN_CD100%_Structure_REV1.pptx',
      'DD도서': '250106-DD100% 도서(창조)',
      '가설구조': '260202-지상2층 가설재 시공 평면도',
    },
    aiOpportunity: '착공 후 현장지원 단계에서 AI 기반 설계 변경 대응 시스템 적용 가능.',
    phase: 2,
  },
  {
    id: 'dc-aws-ve',
    label: 'ICN062 친환경 VE설계',
    labelEn: 'ICN062 VE & Carbon Neutral',
    category: 'project',
    size: 3,
    description: '인천 AWS 데이터센터 친환경 VE설계 및 탄소중립 설계인증 연구(2023-193). 저탄소 자재 적용 및 탄소배출량 산출.',
    details: {
      '프로젝트번호': '2023-193',
      '인증': '탄소중립설계 인증 (대한건축학회)',
      '인증일': '2024년 인증 완료',
      'VE': '친환경 VE설계 보고서',
      '탄소': '별동 탄소배출량 산출 결과 포함',
    },
    aiOpportunity: '탄소배출량 자동 산출 AI. 저탄소 구조재 자동 선정 시스템.',
    phase: 3,
  },

  // ══════════════════════════════════════════════════════
  // 설계 단계
  // ══════════════════════════════════════════════════════
  {
    id: 'phase-concept',
    label: '계획설계',
    labelEn: 'Concept / Schematic',
    category: 'design-phase',
    size: 3,
    description: '구조 시스템 선정, 개략 부재 크기 산정, 경제성 비교. 구조심의 자료 작성 포함.',
    details: {
      '주요산출물': '구조계획보고서, 시스템검토보고서',
      '예시': '구로DC 계획설계보고서(구조).pptx, 구로DC 시스템검토보고서.pptx',
    },
    aiOpportunity: '건물 개요 입력 → 구조 계획안 자동 생성 (Phase 3 목표)',
    phase: 3,
  },
  {
    id: 'phase-dd',
    label: '중간설계',
    labelEn: 'Design Development',
    category: 'design-phase',
    size: 3,
    description: '구조 시스템 확정, 주요 부재 설계, 구조해석 모델 구축. BOD(Basis of Design) 작성.',
    details: {
      '주요산출물': 'BOD 문서, 구조해석 모델, 주요 부재 단면',
      '예시': 'ICN062 BOD & MP 폴더, 김포DC BOD 폴더',
    },
    aiOpportunity: 'midas Gen 자동 모델링 및 부재 단면 최적화 AI (Phase 2 목표)',
    phase: 2,
  },
  {
    id: 'phase-cd',
    label: '실시설계',
    labelEn: 'Construction Documents',
    category: 'design-phase',
    size: 4,
    description: '구조계산서 작성, 구조도면 작성, 배근도 작성. 가장 많은 시간이 소요되는 단계. CD100% 납품.',
    details: {
      '주요산출물': '구조계산서, 구조도면, 배근도, 설계체크리스트',
      '예시': '구로DC 실시설계 구조계산서 724p, ICN062 CD100% 구조도서',
    },
    aiOpportunity: '구조계산서 자동 생성 + 배근도 자동 작성 AI (Phase 1~2 목표)',
    phase: 1,
  },
  {
    id: 'phase-site',
    label: '현장지원',
    labelEn: 'Construction Support',
    category: 'design-phase',
    size: 3,
    description: '설계 변경 검토, 현장 RFI 대응, 구조 안전성 검토. 타워크레인 하중, 장비반입 하중 등 임시 구조 검토.',
    details: {
      '주요업무': '설계변경, RFI 대응, 임시구조 검토',
      '예시': '구로DC 현장지원: 워크플랫폼·크레인하중·코어브레이스 검토',
      '특수검토': '타워크레인 좌대, 장비반입구, 데크 검토',
    },
    aiOpportunity: '설계 변경 자동 반영 및 RFI 자동 응답 AI (Phase 2 목표)',
    phase: 2,
  },
  {
    id: 'phase-safety',
    label: '안전진단',
    labelEn: 'Safety Diagnosis',
    category: 'design-phase',
    size: 3,
    description: '기존 구조물 안전진단. 철근배근탐사, 콘크리트 강도 시험, 구조 안전성 평가.',
    aiOpportunity: '철근배근탐사 판독 AI 자동화, 안전진단 보고서 자동 생성 (Phase 2 목표)',
    phase: 2,
  },

  // ══════════════════════════════════════════════════════
  // 구조 시스템
  // ══════════════════════════════════════════════════════
  {
    id: 'str-rc',
    label: '철근콘크리트조',
    labelEn: 'RC Structure',
    category: 'structure',
    size: 4,
    description: '극한강도설계법(USD) 적용. 데이터센터 지하층 및 코어월 주요 구조 시스템.',
    details: {
      '설계법': '극한강도설계법 (USD)',
      '콘크리트강도': 'fck = 24~49 MPa (층별 차등)',
      '철근': 'SD500 (D10~D13), SD600 (D16~D35)',
      '내진철근': 'SD400S/500S/600S (모멘트골조 주근)',
    },
    aiOpportunity: '배근 자동 최적화 및 배근도 자동 생성 AI 적용 가능.',
  },
  {
    id: 'str-steel',
    label: '철골조',
    labelEn: 'Steel Structure',
    category: 'structure',
    size: 3,
    description: '한계상태설계법 및 허용응력설계법 적용. 바닥 철골보 및 기둥 시스템.',
    details: {
      '설계법': '한계상태설계법 / 허용응력설계법',
      '강재': 'SM275~SM420TMC',
      '볼트': '고력볼트 F10T',
      '앵커': 'SS400, SM490',
    },
    aiOpportunity: '접합부 자동 설계 및 단면 최적화 AI 적용 가능.',
  },
  {
    id: 'str-src',
    label: '철골철근콘크리트조',
    labelEn: 'SRC / CFT Structure',
    category: 'structure',
    size: 3,
    description: 'SRC 기둥 및 CFT(콘크리트충전강관) 기둥 적용. 고층부 수직재 주요 시스템.',
    details: {
      'CFT기둥': '내부 콘크리트 강도 RC기둥과 동일 적용',
      '적용위치': '고층 수직재, 코어 주변',
      '특수사례': '아마존DC CFT기둥 절곡부 검토',
    },
    aiOpportunity: 'CFT 단면 최적화 및 접합 상세 자동 설계 AI 적용 가능.',
  },
  {
    id: 'str-pt',
    label: 'PT 포스트텐션',
    labelEn: 'Post-Tension',
    category: 'structure',
    size: 3,
    description: '강연선(SWPC 7B Low Relaxation) 적용 포스트텐션 슬래브 및 보. 장스팬 구현의 핵심.',
    details: {
      '강연선': 'KS D 7002 SWPC 7B (Low Relaxation)',
      '인장강도': 'fpu = 1,860 MPa',
      '항복강도': 'fpy = 1,580 MPa',
      '긴장력': 'Ppj = 0.75fpu',
      '마찰계수': 'μ = 0.07/rad, κ = 0.00328/m',
      '장기손실': '200 MPa (가정치)',
    },
    aiOpportunity: 'PT 텐던 배치 자동 최적화 및 손실량 자동 계산 AI 적용 가능.',
  },
  {
    id: 'str-composite',
    label: '합성구조',
    labelEn: 'Composite Structure',
    category: 'structure',
    size: 2,
    description: '철골보 + 데크슬래브 합성구조. 데이터센터 지상층 바닥 시스템.',
    aiOpportunity: '합성보 단면 자동 최적화 및 스터드 배치 자동 설계.',
  },
  {
    id: 'str-vbrace',
    label: 'V-브레이스 시스템',
    labelEn: 'V-Brace System',
    category: 'structure',
    size: 2,
    description: '아마존 데이터센터 V-브레이스 다이아그램 적용. 횡력 저항 시스템.',
    details: {
      '적용사례': '아마존 데이터센터 신축공사 V-브레이스',
      '검토자료': '240628 V-브레이스 다이아그램 샘플 모델',
    },
    aiOpportunity: '브레이스 배치 자동 최적화 AI 적용 가능.',
  },

  // ══════════════════════════════════════════════════════
  // 구조 부재 (세분화)
  // ══════════════════════════════════════════════════════
  {
    id: 'mem-slab',
    label: '슬래브',
    labelEn: 'Slab',
    category: 'member',
    size: 3,
    description: 'RC슬래브, 데크슬래브, PT슬래브. 데이터센터 장비하중 대응 핵심 부재.',
    aiOpportunity: '슬래브 배근도 자동 작성 AI (CNP 슬래브 배근도 자동화 프로젝트 연계)',
  },
  {
    id: 'mem-beam',
    label: '보',
    labelEn: 'Beam',
    category: 'member',
    size: 3,
    description: 'RC보, PT보, 철골보, 월거더, 링크빔, 캐노피보.',
    aiOpportunity: '보 단면 자동 최적화 및 접합부 자동 설계 AI 적용 가능.',
  },
  {
    id: 'mem-girder',
    label: '거더',
    labelEn: 'Girder',
    category: 'member',
    size: 2,
    description: '주요 수평 하중 전달 부재. 김포DC 거더 설계용 모델 별도 구축.',
    details: {
      '설계모델': '김포DC 기둥&거더 설계용 모델 (midas Gen)',
      '특이사항': '2층 PT보 RC보로 수정 이력',
    },
    aiOpportunity: '거더 단면 자동 최적화 AI 적용 가능.',
  },
  {
    id: 'mem-column',
    label: '기둥',
    labelEn: 'Column',
    category: 'member',
    size: 3,
    description: 'RC기둥, SRC기둥, CFT기둥. 층별 강도 차등 적용.',
    aiOpportunity: '기둥 단면 최적화 및 층별 강도 자동 산정 AI 적용 가능.',
  },
  {
    id: 'mem-wall',
    label: '벽체·코어',
    labelEn: 'Wall / Core',
    category: 'member',
    size: 3,
    description: '전단벽, 코어월, 버트레스. 내진 저항 시스템의 핵심.',
    aiOpportunity: '내진 성능 자동 평가 및 배근 최적화 AI 적용 가능.',
  },
  {
    id: 'mem-buttress',
    label: '버트레스',
    labelEn: 'Buttress',
    category: 'member',
    size: 2,
    description: '외부 횡력 저항 보강 구조. 김포DC 버트레스 설계 포함.',
    aiOpportunity: '버트레스 단면 자동 최적화 AI 적용 가능.',
  },
  {
    id: 'mem-retaining',
    label: '지하외벽',
    labelEn: 'Retaining Wall',
    category: 'member',
    size: 2,
    description: '지하 흙막이 및 영구 지하외벽. 수압·토압 설계.',
    aiOpportunity: '지하외벽 단면 자동 산정 AI 적용 가능.',
  },
  {
    id: 'mem-foundation',
    label: '기초',
    labelEn: 'Foundation',
    category: 'member',
    size: 3,
    description: '지내력기초 (연암·경암). 설계지지력 Fe ≥ 1,200 kN/m². 말뚝기초 포함.',
    aiOpportunity: '지반 데이터 기반 기초 형식 자동 선정 AI 적용 가능.',
  },

  // ══════════════════════════════════════════════════════
  // 설계 하중 (세분화)
  // ══════════════════════════════════════════════════════
  {
    id: 'load-dead',
    label: '고정하중',
    labelEn: 'Dead Load',
    category: 'load',
    size: 2,
    description: '구조부재 + 마감 + 벽체 하중. 마감 미결정 시 관례 적용.',
    aiOpportunity: '마감 도면 자동 인식 및 하중 자동 산정 AI 적용 가능.',
  },
  {
    id: 'load-live',
    label: '활하중',
    labelEn: 'Live Load',
    category: 'load',
    size: 3,
    description: '용도별 적재하중. 데이터센터 서버랙 하중(10~21 kN/m²) 특수 적용.',
    details: {
      'DATA HALL (2F)': '21.0 kN/m² — 서버랙 집중하중',
      'GENERATOR ROOM (3~7F)': '20.0 kN/m² — 발전기 장비하중',
      'MECHANICAL DECK (2F)': '10.0 kN/m² — 기계설비하중',
      'COLD AIR PLENUM (2F)': '5.0 kN/m² — 공조 플리넘',
      'ELECTRICAL ROOM (2F)': '15.0 kN/m² — 전기설비하중',
      'CORRIDOR / LOBBY': '5.0 kN/m²',
      '일반사무': '2.5 kN/m² (KBC 2019)',
      '출처': 'ICN062 설계하중표 (03-설계하중표 시트)',
    },
    aiOpportunity: '서버랙 배치 변경 시 즉시 구조 재검토 AI 시스템 구축 가능.',
  },
  {
    id: 'load-equip',
    label: '장비하중',
    labelEn: 'Equipment Load',
    category: 'load',
    size: 3,
    description: '기계·전기 장비 집중하중. 발전기, UPS, 냉각장비 등 데이터센터 특수 장비 하중.',
    details: {
      '발전기': '20.0 kN/m² (GENERATOR ROOM)',
      '냉각장비': '기계 전기 장비하중 별도 검토',
      '출처': '인천DC 260305-기계 전기 장비 하중 송부',
    },
    aiOpportunity: '장비 배치 변경 시 즉시 구조 재검토 AI 시스템.',
  },
  {
    id: 'load-wind',
    label: '풍하중',
    labelEn: 'Wind Load',
    category: 'load',
    size: 3,
    description: '기본풍속 Vo=26m/s (서울), 지표면조도 B, 가스트영향계수 계산식 적용.',
    details: {
      '기본풍속': 'Vo = 26 m/s (서울)',
      '지표면조도': 'B',
      '중요도계수': 'Iw = 1.0',
      '가스트계수': 'GDx=1.97, GDy=1.96',
      '설계풍압': 'qH = 505.93 N/m²',
    },
    aiOpportunity: '풍하중 자동 계산 및 midas Gen 자동 입력 AI 적용 가능.',
  },
  {
    id: 'load-seismic',
    label: '지진하중',
    labelEn: 'Seismic Load',
    category: 'load',
    size: 4,
    description: '내진등급 1, 지진구역 Ⅰ (S=0.176g), 지반 S4. 응답스펙트럼해석법 적용.',
    details: {
      '지역계수': 'S = 0.176g (지진구역 Ⅰ)',
      '지반종류': 'S4',
      '내진설계범주': 'C',
      '중요도계수': 'IE = 1.2 (내진등급 1)',
      '저항시스템': 'RC 보통전단벽 (건물골조시스템)',
      '반응수정계수': 'R = 5.0',
      '초과강도계수': 'Ω₀ = 2.5',
      '변위증폭계수': 'Cd = 4.5',
      '해석법': '응답스펙트럼해석법',
    },
    aiOpportunity: '응답스펙트럼해석 자동화 및 내진 성능 자동 평가 AI 적용 가능.',
  },
  {
    id: 'load-snow',
    label: '적설하중',
    labelEn: 'Snow Load',
    category: 'load',
    size: 2,
    description: '기본지상적설하중 Sg=0.5 kN/m², 기본지붕적설하중계수 Cb=0.7.',
    aiOpportunity: '기상 데이터 연동 적설하중 자동 업데이트 시스템 구축 가능.',
  },
  {
    id: 'load-temp',
    label: '온도하중·수압',
    labelEn: 'Temperature / Water Pressure',
    category: 'load',
    size: 2,
    description: '지하구조물 수압·토압 및 온도변화에 의한 하중. 지하수위 EL+5.68m 기준.',
    aiOpportunity: '지하수위 데이터 연동 수압 자동 산정 AI 적용 가능.',
  },
  {
    id: 'load-construction',
    label: '시공하중',
    labelEn: 'Construction Load',
    category: 'load',
    size: 2,
    description: '타워크레인 하중, 장비반입 하중, 콘크리트 타설 하중 등 시공 단계 임시 하중.',
    details: {
      '타워크레인': '부평DC MR608 타워크레인 좌대 검토',
      '장비반입': '구로DC 지상1층 크램쉘·크레인 하중 검토',
      '데크': '구로DC 옥탑층 그레이팅 및 시공하중 검토',
    },
    aiOpportunity: '시공 단계 임시 하중 자동 산정 및 구조 안전성 자동 검토 AI.',
  },

  // ══════════════════════════════════════════════════════
  // 설계 문서 (주요 산출물)
  // ══════════════════════════════════════════════════════
  {
    id: 'doc-calc',
    label: '구조계산서',
    labelEn: 'Structural Calculation Report',
    category: 'document',
    size: 4,
    description: '구조설계의 핵심 산출물. 구로DC 724페이지, ICN062 CD100% 계산서 등. 구조개요·설계하중·구조해석·부재설계 포함.',
    details: {
      '구로DC': '724페이지 실시설계 구조계산서 (REV1)',
      'ICN062': 'CD100% 구조계산서 (04_구조계산서 폴더)',
      '부평DC': '허가변경 구조계산서 (250425)',
      '김포DC': 'CD100% REV.3 계산서 작업 폴더',
    },
    aiOpportunity: '구조계산서 자동 생성 AI (Phase 1~2 핵심 과제). 계산서 검토 AI (Phase 3).',
    phase: 1,
  },
  {
    id: 'doc-drawing',
    label: '구조도면',
    labelEn: 'Structural Drawing',
    category: 'document',
    size: 3,
    description: '구조 평면도, 배근도, 접합상세도. AutoCAD DWG 및 PDF 형식.',
    details: {
      'ICN062': 'CD100% 구조도서 (230925)',
      '부평DC': '철골보 접합상세 (전단·모멘트접합)',
      '김포DC': '하중계획도(LOADING PLAN) PDF',
    },
    aiOpportunity: '구조도면 자동 생성 AI. 도면-계산서 일치여부 AI 검토 (Phase 3).',
    phase: 2,
  },
  {
    id: 'doc-bod',
    label: 'BOD (설계기준서)',
    labelEn: 'Basis of Design',
    category: 'document',
    size: 3,
    description: '설계 기준 및 전제 조건 문서. 발주처 요구사항, 구조 시스템 선정 근거, 재료 기준 포함.',
    details: {
      'ICN062': 'BOD & MP 폴더',
      '김포DC': '[ICN11] BASIS OF DESIGN_STR.pptx',
      '인천DC': 'BASIS OF DESIGN_CD100%_Structure_REV1.pptx',
    },
    aiOpportunity: 'BOD 자동 생성 AI. 발주처 요구사항 자동 분석 및 구조 계획 자동 제안.',
    phase: 3,
  },
  {
    id: 'doc-checklist',
    label: '설계 체크리스트',
    labelEn: 'Design Checklist',
    category: 'document',
    size: 2,
    description: '설계 단계별 검토 항목 체크리스트. 구로DC 설계 CHECKLIST.xlsx 등.',
    details: {
      '구로DC': '221116-LJH-구로데이터센터-설계CHECKLIST.xlsx',
      '김포DC': '250217-ICN11-업무 리스트업-0005.xlsx',
    },
    aiOpportunity: '체크리스트 자동 검토 AI (Phase 3 핵심 과제).',
    phase: 3,
  },
  {
    id: 'doc-report',
    label: '종결·검토 보고서',
    labelEn: 'Final Report',
    category: 'document',
    size: 2,
    description: '프로젝트 종결보고서, 구조 검토 보고서. 구로DC 종결보고서(구조).pptx 등.',
    details: {
      '구로DC': '230612-구로DC-종결보고서(구조).pptx',
      '아마존DC': '240820 RE 아마존 데이터센터 검토의견서',
    },
    aiOpportunity: '보고서 자동 생성 AI (Phase 2~3 목표).',
    phase: 2,
  },
  {
    id: 'doc-fire',
    label: '내화성능설계',
    labelEn: 'Fire Resistance Design',
    category: 'document',
    size: 2,
    description: 'ICN062 내화성능설계 보고서. 부경대·고려대 최종보고서 및 현대 검토의견 포함.',
    details: {
      '보고서': '아마존DC 내화설계 최종보고서 (부경대, 고려대)',
      '검토': '현대 검토의견서 (250210)',
      '프로젝트': '2024-190 ICN062 내화성능설계',
    },
    aiOpportunity: '내화성능 자동 검토 AI 적용 가능.',
    phase: 3,
  },

  // ══════════════════════════════════════════════════════
  // 특수 검토 항목
  // ══════════════════════════════════════════════════════
  {
    id: 'spec-seismic-nonstr',
    label: '비구조요소 내진설계',
    labelEn: 'Non-structural Seismic Design',
    category: 'special',
    size: 2,
    description: 'ICN062 비구조요소 내진설계 보고서. 서버랙, 기계설비, 전기설비 등 비구조요소 내진 고정.',
    aiOpportunity: '비구조요소 내진 고정 자동 검토 AI 적용 가능.',
  },
  {
    id: 'spec-carbon',
    label: '탄소중립 설계인증',
    labelEn: 'Carbon Neutral Certification',
    category: 'special',
    size: 2,
    description: 'ICN062 탄소중립설계 인증 (대한건축학회). 저탄소 자재 적용, 탄소배출량 산출.',
    details: {
      '인증기관': '대한건축학회',
      '인증일': '2024년 완료',
      '내용': '저탄소 자재 VE설계 + 탄소배출량 산출',
    },
    aiOpportunity: '탄소배출량 자동 산출 AI. 저탄소 구조재 자동 선정 시스템.',
    phase: 3,
  },
  {
    id: 'spec-tower-crane',
    label: '타워크레인 구조검토',
    labelEn: 'Tower Crane Structural Review',
    category: 'special',
    size: 2,
    description: '타워크레인 좌대 구조 검토. 부평DC MR608 타워크레인 2호기 기종변경 검토.',
    aiOpportunity: '타워크레인 하중 자동 산정 및 좌대 구조 자동 검토 AI.',
    phase: 2,
  },
  {
    id: 'spec-oil-tank',
    label: '유류탱크 구조',
    labelEn: 'Oil Tank Structure',
    category: 'special',
    size: 2,
    description: '데이터센터 비상발전기용 유류탱크 적재받침대 구조 설계. SHOP 도면 작성.',
    details: {
      '적용': '부평DC 유류탱크 적재받침대 SHOP',
      '도면': '2025.06.02 부평데이터센터 유류탱크 적재받침대 SHOP',
    },
    aiOpportunity: '유류탱크 받침대 구조 자동 설계 AI 적용 가능.',
  },
  {
    id: 'spec-joint',
    label: '접합부 상세설계',
    labelEn: 'Connection Detail Design',
    category: 'special',
    size: 3,
    description: '철골보 전단접합·모멘트접합 상세. 앵커·1절주 접합, CFT기둥 절곡부, 스칼럽 상세.',
    details: {
      '전단접합': '부평DC 철골보 전단접합 상세',
      '모멘트접합': '부평DC 철골보 모멘트접합 상세',
      'CFT절곡부': '아마존DC CFT기둥 절곡부 자료',
      '앵커': '아마존DC 앵커 & 1절주 재승인 도면',
      '스칼럽': '아마존DC 스칼럽 관련 확인 도면',
    },
    aiOpportunity: '접합부 자동 설계 AI (Phase 2~3 목표). 표준 접합부 DB 구축 후 자동 선택.',
    phase: 2,
  },
  {
    id: 'spec-horizontal-pour',
    label: '수평 분리타설',
    labelEn: 'Horizontal Split Casting',
    category: 'special',
    size: 2,
    description: '콘크리트 수평 분리타설 구조 검토. 김포DC 수평 분리타설 검토.',
    aiOpportunity: '분리타설 구조 안전성 자동 검토 AI 적용 가능.',
  },

  // ══════════════════════════════════════════════════════
  // 설계 기준
  // ══════════════════════════════════════════════════════
  {
    id: 'std-kbc',
    label: '건축구조기준 (KBC)',
    labelEn: 'KBC 2019',
    category: 'standard',
    size: 3,
    description: '건축구조기준 (2019, 국토교통부). 구조설계의 최상위 기준. 하중, 재료, 부재설계 전반.',
  },
  {
    id: 'std-kds',
    label: 'KDS 41 내진설계',
    labelEn: 'KDS 41 Seismic',
    category: 'standard',
    size: 2,
    description: 'KDS 41-10-15:2019 내진설계 기준. 지진하중 산정 및 내진 성능 평가 기준.',
  },
  {
    id: 'std-fire',
    label: '내화설계 기준',
    labelEn: 'Fire Resistance Standard',
    category: 'standard',
    size: 2,
    description: '건축물 내화구조 기준. ICN062 내화성능설계 적용 기준.',
  },
  {
    id: 'std-carbon',
    label: '탄소중립 설계인증 기준',
    labelEn: 'Carbon Neutral Standard',
    category: 'standard',
    size: 2,
    description: '대한건축학회 탄소중립설계 인증 기준. ICN062 AWS DC 인증 취득.',
  },

  // ══════════════════════════════════════════════════════
  // 소프트웨어 도구
  // ══════════════════════════════════════════════════════
  {
    id: 'tool-midas',
    label: 'midas Gen',
    labelEn: 'midas Gen',
    category: 'tool',
    size: 3,
    description: '구조해석 소프트웨어. 응답스펙트럼해석, 풍하중 계산 등 구조해석 전 과정 수행. 김포DC 거더·기둥·코어벽체 분리 모델 구축.',
    aiOpportunity: 'midas Gen API 연동 자동 모델링 및 해석 결과 자동 추출 AI 개발 가능.',
  },
  {
    id: 'tool-autocad',
    label: 'AutoCAD / Revit',
    labelEn: 'AutoCAD / Revit',
    category: 'tool',
    size: 2,
    description: '구조도면 및 배근도 작성 도구. AI 연동으로 자동 도면 생성 목표.',
    aiOpportunity: 'AI 생성 배근도를 AutoCAD DXF로 자동 출력하는 파이프라인 구축 가능.',
  },
  {
    id: 'tool-excel',
    label: '설계하중표 (Excel)',
    labelEn: 'Design Load Table (Excel)',
    category: 'tool',
    size: 2,
    description: '설계하중 산정 엑셀 파일. ICN062·김포DC 설계하중표 등.',
    details: {
      'ICN062': '03-설계하중표 시트 (DATA HALL 21kN/m² 등)',
      '김포DC': '250207-RPT-ICN11R-설계하중-0014.xls',
    },
    aiOpportunity: '설계하중표 자동 생성 및 midas Gen 자동 입력 파이프라인.',
  },
  {
    id: 'tool-revit-bim',
    label: 'BIM (Revit 모델)',
    labelEn: 'BIM Model',
    category: 'tool',
    size: 2,
    description: 'ICN062 Revit BIM 모델. 건축·구조 통합 모델 기반 설계.',
    details: {
      'ICN062': '230609-nwd 레빗 모델 공유',
    },
    aiOpportunity: 'BIM 모델 자동 구조해석 모델 변환 AI 적용 가능.',
  },
];

export const GRAPH_LINKS: GraphLink[] = [
  // ── AI 코어 → 4대 영역 ──────────────────────────────
  { source: 'ai-core', target: 'domain-dc',        label: '파일럿', strength: 1.0 },
  { source: 'ai-core', target: 'domain-apt',       label: '2순위',  strength: 0.7 },
  { source: 'ai-core', target: 'domain-highrise',  label: '3순위',  strength: 0.6 },
  { source: 'ai-core', target: 'domain-longspan',  label: '4순위',  strength: 0.5 },

  // ── AI 코어 → AI 로드맵 단계 ────────────────────────
  { source: 'ai-core',   target: 'ai-phase1', strength: 0.9 },
  { source: 'ai-core',   target: 'ai-phase2', strength: 0.8 },
  { source: 'ai-core',   target: 'ai-phase3', strength: 0.7 },
  { source: 'ai-phase1', target: 'ai-phase2', label: '→', strength: 0.9 },
  { source: 'ai-phase2', target: 'ai-phase3', label: '→', strength: 0.9 },

  // ── AI Phase 1 → 세부 과제 ──────────────────────────
  { source: 'ai-phase1', target: 'ai-db-build',     strength: 0.9 },
  { source: 'ai-phase1', target: 'ai-standardize',  strength: 0.9 },

  // ── AI Phase 2 → 세부 과제 ──────────────────────────
  { source: 'ai-phase2', target: 'ai-prelim-section', strength: 0.9 },
  { source: 'ai-phase2', target: 'ai-load-calc',      strength: 0.9 },
  { source: 'ai-phase2', target: 'ai-modeling',       strength: 0.9 },
  { source: 'ai-phase2', target: 'ai-rebar-auto',     strength: 0.8 },
  { source: 'ai-phase2', target: 'ai-safety-diag',    strength: 0.8 },

  // ── AI Phase 3 → 세부 과제 ──────────────────────────
  { source: 'ai-phase3', target: 'ai-section-opt',    strength: 0.9 },
  { source: 'ai-phase3', target: 'ai-change-review',  strength: 0.9 },
  { source: 'ai-phase3', target: 'ai-code-check',     strength: 0.9 },
  { source: 'ai-phase3', target: 'ai-drawing-check',  strength: 0.9 },

  // ── 데이터센터 영역 → 프로젝트 ─────────────────────
  { source: 'domain-dc', target: 'dc-guro',      strength: 0.9 },
  { source: 'domain-dc', target: 'dc-icn062',    strength: 0.9 },
  { source: 'domain-dc', target: 'dc-bupyeong1', strength: 0.8 },
  { source: 'domain-dc', target: 'dc-bupyeong2', strength: 0.8 },
  { source: 'domain-dc', target: 'dc-gimpo',     strength: 0.7 },
  { source: 'domain-dc', target: 'dc-incheon',   strength: 0.7 },
  { source: 'domain-dc', target: 'dc-aws-ve',    strength: 0.6 },

  // ── 프로젝트 → 설계 단계 ────────────────────────────
  { source: 'dc-guro',      target: 'phase-concept', strength: 0.7 },
  { source: 'dc-guro',      target: 'phase-cd',      strength: 0.9 },
  { source: 'dc-guro',      target: 'phase-site',    strength: 0.8 },
  { source: 'dc-icn062',    target: 'phase-dd',      strength: 0.8 },
  { source: 'dc-icn062',    target: 'phase-cd',      strength: 0.9 },
  { source: 'dc-icn062',    target: 'phase-site',    strength: 0.7 },
  { source: 'dc-bupyeong1', target: 'phase-cd',      strength: 0.8 },
  { source: 'dc-bupyeong1', target: 'phase-site',    strength: 0.8 },
  { source: 'dc-bupyeong2', target: 'phase-dd',      strength: 0.7 },
  { source: 'dc-bupyeong2', target: 'phase-cd',      strength: 0.8 },
  { source: 'dc-gimpo',     target: 'phase-cd',      strength: 0.9 },
  { source: 'dc-incheon',   target: 'phase-cd',      strength: 0.8 },
  { source: 'dc-incheon',   target: 'phase-site',    strength: 0.7 },
  { source: 'dc-aws-ve',    target: 'phase-cd',      strength: 0.6 },

  // ── 프로젝트 → 구조 시스템 ──────────────────────────
  { source: 'dc-guro',      target: 'str-rc',        strength: 0.9 },
  { source: 'dc-guro',      target: 'str-steel',     strength: 0.8 },
  { source: 'dc-guro',      target: 'str-src',       strength: 0.7 },
  { source: 'dc-guro',      target: 'str-pt',        strength: 0.8 },
  { source: 'dc-icn062',    target: 'str-rc',        strength: 0.9 },
  { source: 'dc-icn062',    target: 'str-steel',     strength: 0.7 },
  { source: 'dc-bupyeong2', target: 'str-steel',     strength: 0.9 },
  { source: 'dc-bupyeong2', target: 'str-vbrace',    strength: 0.7 },
  { source: 'dc-gimpo',     target: 'str-rc',        strength: 0.8 },
  { source: 'dc-gimpo',     target: 'str-pt',        strength: 0.7 },

  // ── 구조 시스템 → 부재 ──────────────────────────────
  { source: 'str-rc',        target: 'mem-slab',       strength: 0.8 },
  { source: 'str-rc',        target: 'mem-beam',       strength: 0.8 },
  { source: 'str-rc',        target: 'mem-column',     strength: 0.8 },
  { source: 'str-rc',        target: 'mem-wall',       strength: 0.9 },
  { source: 'str-rc',        target: 'mem-retaining',  strength: 0.7 },
  { source: 'str-rc',        target: 'mem-foundation', strength: 0.7 },
  { source: 'str-steel',     target: 'mem-beam',       strength: 0.9 },
  { source: 'str-steel',     target: 'mem-girder',     strength: 0.9 },
  { source: 'str-steel',     target: 'mem-column',     strength: 0.7 },
  { source: 'str-src',       target: 'mem-column',     strength: 0.9 },
  { source: 'str-pt',        target: 'mem-slab',       strength: 0.9 },
  { source: 'str-pt',        target: 'mem-beam',       strength: 0.8 },
  { source: 'str-composite', target: 'mem-slab',       strength: 0.9 },
  { source: 'str-composite', target: 'mem-beam',       strength: 0.9 },
  { source: 'str-vbrace',    target: 'mem-wall',       strength: 0.8 },
  { source: 'str-rc',        target: 'mem-buttress',   strength: 0.7 },

  // ── 하중 → 부재 ─────────────────────────────────────
  { source: 'load-live',         target: 'mem-slab',       label: '지배', strength: 0.9 },
  { source: 'load-equip',        target: 'mem-slab',       label: '집중', strength: 0.9 },
  { source: 'load-equip',        target: 'mem-beam',       strength: 0.8 },
  { source: 'load-seismic',      target: 'mem-wall',       label: '지배', strength: 0.9 },
  { source: 'load-seismic',      target: 'mem-column',     strength: 0.7 },
  { source: 'load-wind',         target: 'mem-wall',       strength: 0.7 },
  { source: 'load-wind',         target: 'mem-buttress',   strength: 0.8 },
  { source: 'load-dead',         target: 'mem-foundation', strength: 0.8 },
  { source: 'load-temp',         target: 'mem-retaining',  strength: 0.9 },
  { source: 'load-construction', target: 'mem-slab',       strength: 0.7 },

  // ── 설계 단계 → 문서 ────────────────────────────────
  { source: 'phase-concept', target: 'doc-bod',       strength: 0.8 },
  { source: 'phase-dd',      target: 'doc-bod',       strength: 0.9 },
  { source: 'phase-cd',      target: 'doc-calc',      strength: 0.9 },
  { source: 'phase-cd',      target: 'doc-drawing',   strength: 0.9 },
  { source: 'phase-cd',      target: 'doc-checklist', strength: 0.8 },
  { source: 'phase-site',    target: 'doc-report',    strength: 0.8 },

  // ── 특수 검토 → 프로젝트/부재 ──────────────────────
  { source: 'spec-joint',          target: 'str-steel',    strength: 0.9 },
  { source: 'spec-joint',          target: 'str-src',      strength: 0.8 },
  { source: 'spec-oil-tank',       target: 'dc-bupyeong1', strength: 0.9 },
  { source: 'spec-oil-tank',       target: 'dc-bupyeong2', strength: 0.9 },
  { source: 'spec-tower-crane',    target: 'load-construction', strength: 0.9 },
  { source: 'spec-seismic-nonstr', target: 'load-seismic', strength: 0.8 },
  { source: 'spec-carbon',         target: 'dc-aws-ve',    strength: 0.9 },
  { source: 'spec-carbon',         target: 'std-carbon',   strength: 0.9 },
  { source: 'std-carbon',          target: 'dc-icn062',    label: '인증취득', strength: 0.8 },
  { source: 'spec-horizontal-pour',target: 'dc-gimpo',     strength: 0.9 },
  { source: 'doc-fire',            target: 'dc-icn062',    strength: 0.9 },
  { source: 'doc-fire',            target: 'std-fire',     strength: 0.9 },

  // ── 설계 기준 → 하중 ────────────────────────────────
  { source: 'std-kbc', target: 'load-wind',    strength: 0.8 },
  { source: 'std-kbc', target: 'load-seismic', strength: 0.8 },
  { source: 'std-kbc', target: 'load-snow',    strength: 0.7 },
  { source: 'std-kbc', target: 'load-live',    strength: 0.8 },
  { source: 'std-kds', target: 'load-seismic', strength: 0.9 },

  // ── 소프트웨어 → 설계 단계 ──────────────────────────
  { source: 'tool-midas',    target: 'phase-dd',  strength: 0.9 },
  { source: 'tool-midas',    target: 'phase-cd',  strength: 0.8 },
  { source: 'tool-autocad',  target: 'phase-cd',  strength: 0.9 },
  { source: 'tool-excel',    target: 'load-live', strength: 0.9 },
  { source: 'tool-excel',    target: 'load-equip',strength: 0.8 },
  { source: 'tool-revit-bim',target: 'phase-dd',  strength: 0.8 },
  { source: 'tool-revit-bim',target: 'tool-midas',strength: 0.7 },

  // ── AI 세부 과제 → 설계 단계/부재/문서 ─────────────
  { source: 'ai-db-build',      target: 'doc-calc',      label: 'DB화',   strength: 0.9 },
  { source: 'ai-db-build',      target: 'doc-drawing',   label: 'DB화',   strength: 0.8 },
  { source: 'ai-standardize',   target: 'phase-cd',      label: '표준화', strength: 0.8 },
  { source: 'ai-load-calc',     target: 'load-live',     label: '자동화', strength: 0.9 },
  { source: 'ai-load-calc',     target: 'load-equip',    label: '자동화', strength: 0.9 },
  { source: 'ai-load-calc',     target: 'tool-excel',    label: '대체',   strength: 0.8 },
  { source: 'ai-modeling',      target: 'tool-midas',    label: '자동화', strength: 0.9 },
  { source: 'ai-rebar-auto',    target: 'mem-slab',      label: '자동작성',strength: 0.9 },
  { source: 'ai-rebar-auto',    target: 'doc-drawing',   label: '자동생성',strength: 0.9 },
  { source: 'ai-prelim-section',target: 'mem-column',    label: '자동추출',strength: 0.8 },
  { source: 'ai-prelim-section',target: 'mem-beam',      label: '자동추출',strength: 0.8 },
  { source: 'ai-section-opt',   target: 'mem-column',    label: '최적화', strength: 0.9 },
  { source: 'ai-section-opt',   target: 'mem-beam',      label: '최적화', strength: 0.9 },
  { source: 'ai-section-opt',   target: 'mem-slab',      label: '최적화', strength: 0.8 },
  { source: 'ai-change-review', target: 'doc-calc',      label: 'AI검토', strength: 0.9 },
  { source: 'ai-code-check',    target: 'std-kbc',       label: 'AI검토', strength: 0.9 },
  { source: 'ai-code-check',    target: 'std-kds',       label: 'AI검토', strength: 0.9 },
  { source: 'ai-drawing-check', target: 'doc-drawing',   label: 'AI검토', strength: 0.9 },
  { source: 'ai-drawing-check', target: 'doc-calc',      label: 'AI검토', strength: 0.9 },
  { source: 'ai-safety-diag',   target: 'phase-safety',  label: '자동화', strength: 0.9 },
];
